# Generated by Django 5.1.7 on 2025-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('incident_date', models.DateTimeField(auto_now_add=True)),
                ('incident_location', models.CharField(max_length=255)),
            ],
        ),
    ]
