# Generated by Django 5.1.7 on 2025-03-20 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoría de incidente',
                'verbose_name_plural': 'Categorías de incidentes',
            },
        ),
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de incidente',
                'verbose_name_plural': 'Tipos de incidentes',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255, verbose_name='Nombre del Permiso/Perfil')),
                ('permission_elevate', models.BooleanField(default=False, verbose_name='Usuario con permisos Elevados')),
                ('permission_reporte_semanal_herramienta', models.BooleanField(default=False, verbose_name='Reporte Semanal Herramientas')),
                ('permission_reporte_quincenal_biometrico', models.BooleanField(default=False, verbose_name='Reporte Quincenal Biométricos')),
                ('permission_reporte_semanal_drones', models.BooleanField(default=False, verbose_name='Reporte Semanal Drones')),
                ('permission_reporte_semanal_cctv820', models.BooleanField(default=False, verbose_name='Reporte Semanal CCTV 820')),
                ('permission_reporte_mantenimiento_drone', models.BooleanField(default=False, verbose_name='Reporte Mantenimiento Drones')),
                ('permission_boletin_ciberseguridad', models.BooleanField(default=False, verbose_name='Boletín de Ciberseguridad')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='BoletinCiberseguridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='boletin_ciberseguridad/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Boletín de ciberseguridad',
                'verbose_name_plural': 'Boletines de ciberseguridad',
            },
        ),
        migrations.CreateModel(
            name='ReporteMantenimientoDrone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='reporte_mantenimiento_drones/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Reporte Mantenimiento Drone',
                'verbose_name_plural': 'Reportes Mantenimiento Drones',
            },
        ),
        migrations.CreateModel(
            name='ReporteQuincenalBiometrico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='reporte_quincenal_biometrico/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Reporte biométrico',
                'verbose_name_plural': 'Reportes biométricos',
            },
        ),
        migrations.CreateModel(
            name='ReporteSemanalCCTV820',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='reporte_semanal_cctv820/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Reporte CCTV 820',
                'verbose_name_plural': 'Reportes CCTV 820',
            },
        ),
        migrations.CreateModel(
            name='ReporteSemanalDrones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='reporte_semanal_drones/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Reporte Drone',
                'verbose_name_plural': 'Reportes Drones',
            },
        ),
        migrations.CreateModel(
            name='ReporteSemanalHerramienta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='reporte_semanal_herramienta/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
            options={
                'verbose_name': 'Reporte Herramienta',
                'verbose_name_plural': 'Reportes Herramientas',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.permission', verbose_name='Permisos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de usuario',
                'verbose_name_plural': 'Permisos de usuarios',
            },
        ),
    ]
