# Generated by Django 5.1.7 on 2025-03-20 01:48

import django.db.models.deletion
import incident.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_description', models.TextField()),
                ('incident_date', models.DateTimeField(auto_now_add=True)),
                ('incident_file', models.FileField(blank=True, null=True, upload_to=incident.models.upload_file_path)),
                ('incident_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('incident_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
                ('incident_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('incident_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidentcategory')),
                ('incident_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidentlocation')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidenttype')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
