# Generated by Django 5.1.7 on 2025-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_image',
            field=models.FileField(blank=True, null=True, upload_to='incident_files/'),
        ),
    ]
