# Generated by Django 5.1.7 on 2025-03-20 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'Incidente', 'verbose_name_plural': 'Incidentes'},
        ),
        migrations.AlterModelOptions(
            name='incidentcategory',
            options={'verbose_name': 'Categoría de incidente', 'verbose_name_plural': 'Categorías de incidentes'},
        ),
        migrations.AlterModelOptions(
            name='incidentlocation',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='incidenttype',
            options={'verbose_name': 'Tipo de incidente', 'verbose_name_plural': 'Tipos de incidentes'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='userpermition',
            options={'verbose_name': 'Permiso de usuario', 'verbose_name_plural': 'Permisos de usuarios'},
        ),
        migrations.AddField(
            model_name='userpermition',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='userpermition',
            name='is_viewer',
            field=models.BooleanField(default=False, verbose_name='Visualizador'),
        ),
        migrations.AlterField(
            model_name='userpermition',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='userpermition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='userpermition',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.permission', verbose_name='Permiso'),
        ),
        migrations.AlterField(
            model_name='userpermition',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
