# Generated by Django 5.1.7 on 2025-03-20 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletinciberseguridad',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='boletinciberseguridad',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='boletinciberseguridad',
            name='pdf_file',
            field=models.FileField(upload_to='boletin_ciberseguridad/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='boletinciberseguridad',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Sucursal'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='incidentcategory',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Categoría de incidente'),
        ),
        migrations.AlterField(
            model_name='incidentlocation',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='incident_type',
            field=models.CharField(max_length=255, verbose_name='Tipo de incidente'),
        ),
        migrations.AlterField(
            model_name='reportemantenimientodrone',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='reportemantenimientodrone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='reportemantenimientodrone',
            name='pdf_file',
            field=models.FileField(upload_to='reporte_mantenimiento_drones/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='reportemantenimientodrone',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='reportequincenalbiometrico',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='reportequincenalbiometrico',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='reportequincenalbiometrico',
            name='pdf_file',
            field=models.FileField(upload_to='reporte_quincenal_biometrico/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='reportequincenalbiometrico',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='reportesemanalcctv820',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='reportesemanalcctv820',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='reportesemanalcctv820',
            name='pdf_file',
            field=models.FileField(upload_to='reporte_semanal_cctv820/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='reportesemanalcctv820',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='reportesemanaldrones',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='reportesemanaldrones',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='reportesemanaldrones',
            name='pdf_file',
            field=models.FileField(upload_to='reporte_semanal_drones/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='reportesemanaldrones',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='reportesemanalherramienta',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='reportesemanalherramienta',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='reportesemanalherramienta',
            name='pdf_file',
            field=models.FileField(upload_to='reporte_semanal_herramienta/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='reportesemanalherramienta',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.CreateModel(
            name='ReporteIncidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de reporte')),
                ('pdf_file', models.FileField(upload_to='reporte_incidente/', verbose_name='Archivo PDF')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.branch', verbose_name='Sucursal')),
                ('categoria_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidentcategory', verbose_name='Categoría de reporte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.company', verbose_name='Empresa')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidenttype', verbose_name='Tipo de reporte')),
            ],
            options={
                'verbose_name': 'Reporte de incidente',
                'verbose_name_plural': 'Reportes de incidentes',
            },
        ),
    ]
