# Generated by Django 5.1.7 on 2025-03-20 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_branch_options_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermition',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userpermition',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userpermition',
            name='is_supervisor',
        ),
        migrations.RemoveField(
            model_name='userpermition',
            name='is_viewer',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_is_viewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpermition',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.permission', verbose_name='Permisos'),
        ),
    ]
