# Generated by Django 5.1.7 on 2025-03-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_alter_boletinciberseguridad_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusReporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=255, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Estatus de reporte',
                'verbose_name_plural': 'Estatus de reportes',
            },
        ),
        migrations.AddField(
            model_name='reporteincidente',
            name='estatus_reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.estatusreporte', verbose_name='Estatus de reporte'),
        ),
    ]
