# Generated by Django 5.1.7 on 2025-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_incident_incident_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_category',
            field=models.CharField(choices=[('Accidente', 'Accidente'), ('Incendio', 'Incendio'), ('Robo', 'Robo'), ('Otros', 'Otros')], default='Accidente', max_length=15),
        ),
    ]
