# Generated by Django 5.1.7 on 2025-03-19 16:44

import django.db.models.deletion
import incident.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_incident_incident_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_video',
            field=models.FileField(blank=True, null=True, upload_to=incident.models.upload_video_path),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_image',
            field=models.ImageField(blank=True, null=True, upload_to=incident.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidentcategory'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidentlocation'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident.incidenttype'),
        ),
    ]
