# Generated by Django 5.1.7 on 2025-03-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_estatusreporte_reporteincidente_estatus_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportemantenimientodrone',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='reportemantenimientodrone',
            name='company',
        ),
        migrations.RemoveField(
            model_name='reportequincenalbiometrico',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='reportequincenalbiometrico',
            name='company',
        ),
        migrations.RemoveField(
            model_name='reportesemanalcctv820',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='reportesemanalcctv820',
            name='company',
        ),
        migrations.RemoveField(
            model_name='reportesemanaldrones',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='reportesemanaldrones',
            name='company',
        ),
        migrations.RemoveField(
            model_name='reportesemanalherramienta',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='reportesemanalherramienta',
            name='company',
        ),
        migrations.DeleteModel(
            name='BoletinCiberseguridad',
        ),
        migrations.DeleteModel(
            name='ReporteMantenimientoDrone',
        ),
        migrations.DeleteModel(
            name='ReporteQuincenalBiometrico',
        ),
        migrations.DeleteModel(
            name='ReporteSemanalCCTV820',
        ),
        migrations.DeleteModel(
            name='ReporteSemanalDrones',
        ),
        migrations.DeleteModel(
            name='ReporteSemanalHerramienta',
        ),
    ]
