# Generated by Django 5.1.7 on 2025-03-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_remove_reportemantenimientodrone_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission_boletin_ciberseguridad',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_reporte_mantenimiento_drone',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_reporte_quincenal_biometrico',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_reporte_semanal_cctv820',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_reporte_semanal_drones',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permission_reporte_semanal_herramienta',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_reporte_incidente',
            field=models.BooleanField(default=False, verbose_name='Reporte de Incidentes'),
        ),
    ]
