# Generated by Django 5.1.7 on 2025-03-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_incidentcategory_incidentlocation_incidenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=255)),
                ('client_phone', models.CharField(max_length=255)),
                ('client_address', models.CharField(max_length=255)),
            ],
        ),
    ]
