# Generated by Django 5.1.7 on 2025-03-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_remove_permission_permission_boletin_ciberseguridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_elevate',
            field=models.BooleanField(default=False, verbose_name='Usuario con permisos Elevados'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission_reporte_incidente',
            field=models.BooleanField(default=False, verbose_name='Reporte de Incidentes'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
