# Generated by Django 5.1.7 on 2025-03-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0005_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
    ]
