# Generated by Django 5.1.7 on 2025-03-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0006_remove_client_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incident.client'),
        ),
    ]
